#pragma once

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define BACKGROUND_COLOR_WHITE D3DCOLOR_XRGB(255, 255, 255)
#define SCREEN_WIDTH 260
#define SCREEN_HEIGHT 260
#define UPDATE_RANGE 480
#define MAX_FRAME_RATE 200
#define WINDOW_CLASS_NAME L"MainWindow"
#define MAIN_WINDOW_TITLE L"Castle Vania"

#define STAGE_1_WIDTH 768
#define STAGE_2_WIDTH 2060
#define STAGE_3_WIDTH 524
#define STAGE_4_WIDTH 528
#define STAGE_5_WIDTH 780
#define ZONE_WIDTH 270
//Object type
#define GO_TYPE_SIMON 1
#define GO_TYPE_BRICK 2
#define GO_TYPE_BACKGROUND 3
#define GO_TYPE_MORNINGSTAR 4
#define GO_TYPE_MICS 5
#define GO_TYPE_ENEMY 6
#define GO_TYPE_ZOMBIE 6
#define GO_TYPE_DOG 7
#define GO_TYPE_BAT 8
#define GO_TYPE_FISH 9
#define GO_TYPE_ITEM 10
#define GO_TYPE_SUBWEAPON 11
#define GO_TYPE_STAIR 12
#define GO_TYPE_EFFECT 13
#define GO_TYPE_EFFECT_BULLET 14
#define GO_TYPE_BOSS 15
//loadsprite_action
#define LOADSPRITE_ACTION_LOAD_FILE 0
#define LOADSPRITE_ACTION_ADD_SPRITE 1
#define LOADSPRITE_ACTION_ADD_ANIMATION 2
//textures id
#define ID_TEX_SIMON 0
#define ID_TEX_SIMON_EXTRA 1
#define ID_TEX_SIMON_DIE 5
//UI will be 10
#define ID_TEX_BRICK 20
#define ID_TEX_BRICK_2 22
#define ID_TEX_BRICK_3 23
#define ID_TEX_BRICK_4 24
#define ID_TEX_BRICK_5 25
#define ID_TEX_BACKGROUND 30
#define ID_TEX_BACKGROUND2 32
#define ID_TEX_BACKGROUND3 33
#define ID_TEX_MORNINGSTAR 40
#define ID_TEX_MICS_1 50
#define ID_TEX_MICS_2 51
#define ID_TEX_DESTROY_AFFECT 52
#define ID_TEX_ENEMY_ZOMBIE 60
#define ID_TEX_ENEMY_DOG 61
#define ID_TEX_ENEMY_BAT 62
#define ID_TEX_ENEMY_FISH 63
#define ID_TEX_ENEMY_BOSS 64
#define ID_TEX_ITEM_0 700 //heart small
#define ID_TEX_ITEM_1 701 //heart big
#define ID_TEX_ITEM_2 702 //money bag
#define ID_TEX_ITEM_3 703 //morning star
#define ID_TEX_ITEM_4 704 //sword
#define ID_TEX_ITEM_5 705 //clock
#define ID_TEX_ITEM_6 706 //
#define ID_TEX_ITEM_7 707
#define ID_TEX_ITEM_8 708
#define ID_TEX_ITEM_9 709
#define ID_TEX_ITEM_10 710
#define ID_TEX_ITEM_11 711 
#define ID_TEX_ITEM_12 712
#define ID_TEX_ITEM_17 717

#define ID_TEX_SUBWEAPON_1 713
#define ID_TEX_SUBWEAPON_2 714
#define ID_TEX_SUBWEAPON_3 715 
#define ID_TEX_SUBWEAPON_4 716



#define ID_TEX_EFFECT_1 130
#define ID_TEX_EFFECT_2 131
#define ID_TEX_EFFECT_BULLET 132


//background id lv1
#define ID_TEX_BACKGROUND_0 300
#define ID_TEX_BACKGROUND_1 301
#define ID_TEX_BACKGROUND_2 302
#define ID_TEX_BACKGROUND_3 303
#define ID_TEX_BACKGROUND_4 304
//

//background
#define MODIFY_WIDTH 10
#define CELL_WIDTH 16

//stage
#define ZONE_WIDTH 130
#define SCREEN_WIDTH 260

#define SIMON_WALKING_SPEED			0.075f
//#define SIMON_WALKING_SPEED			0.3f

#define SIMON_JUMP_SPEED_Y			0.3f
#define SIMON_JUMP_DEFLECT_SPEED	0.05f
#define SIMON_GRAVITY				0.001f
#define SIMON_DIE_DEFLECT_SPEED		0.5f
#define SIMON_UNTOUCHABLE_TIME  3000
#define SIMON_TAKINGDAME_TIME  500

#define SIMON_STATE_IDLE_BEHIDE		0
#define SIMON_STATE_IDLE			100
#define SIMON_STATE_WALKING_RIGHT	200
#define SIMON_STATE_WALKING_LEFT	300
// #define SIMON_STATE_QUY_RIGHT		400
#define SIMON_STATE_QUY				400
#define SIMON_STATE_QUY_LEFT		500
#define SIMON_STATE_ATTACK_RIGHT	600
#define SIMON_STATE_ATTACK_LEFT		700
#define SIMON_STATE_DIE				800
#define SIMON_STATE_JUMP			900
#define SIMON_STATE_ATTACK			1000
#define SIMON_STATE_UP_STAIR_RIGHT	1100
#define SIMON_STATE_UP_STAIR_LEFT	1200
#define SIMON_STATE_DOWN_STAIR_RIGHT 1300
#define SIMON_STATE_DOWN_STAIR_LEFT	1400
#define SIMON_STATE_GO_ON_STAIR		1500
#define SIMON_STATE_UP_STAIR_IDLE	1600
#define SIMON_STATE_DOWN_STAIR_IDLE	1700


#define SIMON_ANI_IDLE_BEHIDE			0
#define SIMON_ANI_IDLE_RIGHT			1
#define SIMON_ANI_IDLE_LEFT				2
#define SIMON_ANI_QUY_RIGHT				3
#define SIMON_ANI_QUY_LEFT				4
#define SIMON_ANI_WALKING_RIGHT			5
#define SIMON_ANI_WALKING_LEFT			6
#define SIMON_ANI_ATTACK_RIGHT			7
#define SIMON_ANI_ATTACK_LEFT			8
#define SIMON_ANI_DIE					9
#define SIMON_ANI_JUMP_RIGHT			10	
#define SIMON_ANI_JUMP_LEFT				11
#define SIMON_ANI_IDLE_RIGHT_UP_STAIR	12	
#define SIMON_ANI_IDLE_LEFT_UP_STAIR	13
#define SIMON_ANI_IDLE_RIGHT_DOWN_STAIR	14	
#define SIMON_ANI_IDLE_LEFT_DOWN_STAIR	15
#define SIMON_ANI_RIGHT_UP_STAIR		16	
#define SIMON_ANI_LEFT_UP_STAIR			17
#define SIMON_ANI_RIGHT_DOWN_STAIR		18	
#define SIMON_ANI_LEFT_DOWN_STAIR		19
#define SIMON_ANI_TAKING_DAMAGE_LEFT	20
#define SIMON_ANI_TAKING_DAMAGE_RIGHT	21
#define SIMON_ANI_INVI_LEFT				22
#define SIMON_ANI_INVI_RIGHT			23


#define SIMON_ACTION_GO_ON_STAIR 1
#define SIMON_STAND_BBOX_WIDTH  16
#define SIMON_STAND_BBOX_HEIGHT 32

#define SIMON_ATTACK_DURATION 450
#define SIMON_TIME_TO_DISPLAY_LAST_FRAME 300


#define STAGE1_TEXT_NO 48
#define STAGE2_TEXT_NO 176
#define STAGE3_TEXT_NO 52
#define STAGE4_TEXT_NO 32
#define STAGE5_TEXT_NO 48


#define DOG_STATE_IDLE 1
#define DOG_STATE_MOVE 2
#define DOG_STATE_JUMP 3
#define DOG_STATE_MOVE_AFTER_JUMP 4
#define DOG_SPEED 0.11
#define BAT_STATE_FLY_UP 1
#define BAT_STATE_FLY_DOWN 2
#define FISH_STATE_JUMP 1
#define FISH_STATE_MOVE 2
#define FISH_STATE_ATTACK 3

#define WEAPON_FIRE_LASTING 1000

#define WEAPON_STATE_FIRE_BURN 81
#define STOP_ENEMY_LASTING 3000


#define EFFECT_GRAVITY 0.012f
#define ITEM_GRAVITY 0.008f
#define BASE_GRAVITY 0.002f

#define BULLET_SPEED 0.075
#define BULLET_DAMAGE 1

#define ZOMBIE_MOVE_SPEED 0.075
#define BAT_MOVE_SPEED 0.075
#define BAT_MOVE_UP_SPEED -0.03
#define BAT_MOVE_DOWN_SPEED 0.03
#define FISH_JUMP_SPEED 0.35f
#define FISH_MOVE_SPEED 0.04f
#define FISH_ATTACK_COOLDOWN 3000
#define FISH_ATTACK_DURATION 1000
#define FISH_ATTACK_TIME 500

#define DESTROY_TIME 190

#define BOSS_STATE_SLEEP 1
#define BOSS_STATE_IDLE 2
#define BOSS_STATE_MOVE 3
#define BOSS_STATE_ATTACK 4
#define BOSS_STATE_RANGE_ATTACK 5
#define BOSS_TOTAL_MOVING_DISTANCE 240
#define BOSS_ACTION_COOLDOWN_TIME 1500
#define BOSS_MOVE_SPEED 0.02
#define BOSS_ATTACK_MOVE_SPEED 0.1


//item id
#define SMALL_HEART_ID 0
#define BIG_HEART_ID 1
#define BAG_1_ID 20
#define BAG_2_ID 21
#define BAG_3_ID 22
#define MORNING_STAR_ID 3
#define SWORD_ID 4
#define CLOCK_ID 5
#define NECKLET_ID 6
#define AXE_ID 7
#define FIRE_BOTTLE_ID 8
#define CHICKEN_ID 9
#define INVI_POTION_ID 10
#define INVI_DURATION 6000
//mics id
#define FIRE_STATUE_ID 1
#define CANDLE_ID 2

//enemy id
#define ZOMBIE_ID 1
#define DOG_ID 2
#define BAT_ID 3
#define FISH_ID 4

//intro


//brick
#define BRICK_UNABLE_DESTROY -1
#define BRICK_UNABLE_DROP_ITEM -2

